### ISSUE TITLE
Contact form size

### ISSUE THREAD

**Issue by LucasCtrl** [LucasCtrl/Portfolio#8]
# Request
In the contact form, the textarea is a little bit small in height, can you increase it size?

**Comment by ghost** [comment]
you can add a css like : `<textarea style="height:250px;" />`
or add the following proprieties of textarea :  `<textarea rows="20" />`

**Comment by LucasCtrl** [comment]
The textarea still have the same height with `<textarea rows="6" />`
I need to fix it with some CSS tomorrow.

**Comment by ghost** [comment]
you can add your custom class contains the height of textarea if you want, like :
```
<style>
       .myclass{
               height : 250px !important;
       }
</style>
```
and then add your class to your textarea : 
`<textarea class="myclass"></textarea>`

**Comment by LucasCtrl** [comment]
Fixed with commit [https://github.com/LucasCtrl/Portfolio/commit/11cbddb4a7c6f83449d184729c9d8e5f7e76e2f7](https://github.com/LucasCtrl/Portfolio/commit/11cbddb4a7c6f83449d184729c9d8e5f7e76e2f7)
